# Generated by Django 4.1.4 on 2022-12-25 15:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('bio', models.TextField(null=True)),
                ('verified', models.BooleanField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
