# Generated by Django 4.1.4 on 2023-02-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='from_user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FriendList',
            },
        ),
    ]
